version: '3.7'
services:
  familycosts:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '3000:3000'
    restart: 'on-failure'
    networks:
      - sa-network
    environment:
      - MONGO_DB=mongodb://mongo:27017/voting
      - JWT_SECRET=obligatorioarquitectura2022m8arodriguezsottosecinaro
      # - LOG_FILE_PATH=/var/log/log.txt
    volumes:
      # - './dockercompose/familyCosts/:/var/log'
      - '../:/usr/src/app'
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - './dockercompose/mongo/:/data/db'
    restart: 'on-failure'
    ports:
      - '27017:27017'
    networks:
      - sa-network

networks:
  sa-network:
    name: sa-network
    driver: bridge
